import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { Poppins } from "next/font/google";
import { BackgroundLines } from "@/components/ui/background-lines";
import { Analytics } from "@vercel/analytics/next"
import { SpeedInsights } from "@vercel/speed-insights/next"
import DatabaseInitializer from "@/components/DatabaseInitializer"
import { CartProvider } from "@/contexts/CartContext"



const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});


export const metadata: Metadata = {
  title: "Fidgi world",
  description: "Generated by Fidgi world",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={`${poppins.className} antialiased  `}>
        <CartProvider>
          <DatabaseInitializer />
          {/* <BackgroundLines> */}
          {/* <Navbar /> */}
          {children}
          {/* </BackgroundLines> */}
        </CartProvider>
        <Analytics/>
        <SpeedInsights/>
      </body>
    </html>
  );
}
