import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { Poppins } from "next/font/google";
import { BackgroundLines } from "@/components/ui/background-lines";
import { Analytics } from "@vercel/analytics/next"
import { SpeedInsights } from "@vercel/speed-insights/next"



const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={`${poppins.className} antialiased  `}>
        <BackgroundLines>
        <Navbar />
        {children}
        </BackgroundLines>
        <Analytics/>
        <SpeedInsights/>
      </body>
    </html>
  );
}
